"""Initial schema

Revision ID: 66873ae7d5b3
Revises: 
Create Date: 2026-03-02 04:25:17.763731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66873ae7d5b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('rfc', sa.String(length=13), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=200), nullable=True),
    sa.Column('dias_credito', sa.Integer(), nullable=True),
    sa.Column('limite_credito', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('estatus', sa.Enum('ACTIVO', 'INACTIVO', 'SUSPENDIDO', name='clientstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_is_deleted'), 'clients', ['is_deleted'], unique=False)
    op.create_table('dollies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_economico', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('placas', sa.String(length=15), nullable=True),
    sa.Column('estatus', sa.Enum('DISPONIBLE', 'EN_USO', 'TALLER', 'BAJA', name='unitstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_economico')
    )
    op.create_index(op.f('ix_dollies_is_deleted'), 'dollies', ['is_deleted'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('licencia_numero', sa.String(length=50), nullable=True),
    sa.Column('licencia_tipo', sa.String(length=20), nullable=True),
    sa.Column('licencia_vigencia', sa.Date(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('salario_base', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('apto_medico', sa.String(length=100), nullable=True),
    sa.Column('apto_medico_vigencia', sa.Date(), nullable=True),
    sa.Column('estatus', sa.Enum('ACTIVO', 'INACTIVO', 'VACACIONES', name='driverstatus', native_enum=False), nullable=False),
    sa.Column('foto', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_is_deleted'), 'drivers', ['is_deleted'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.Enum('refacciones', 'combustible', 'insumos', 'herramientas', 'llantas', 'lubricantes', 'otro', name='inventorycategory'), nullable=False),
    sa.Column('unidad_medida', sa.String(length=20), nullable=False),
    sa.Column('stock_actual', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('stock_maximo', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('costo_promedio', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ultimo_costo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_inventory_items_is_deleted'), 'inventory_items', ['is_deleted'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_is_deleted'), 'roles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('rfc', sa.String(length=13), nullable=True),
    sa.Column('tipo', sa.Enum('COMBUSTIBLE', 'REFACCIONES', 'SERVICIOS', 'CASETAS', 'OTRO', name='suppliertype', native_enum=False), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=200), nullable=True),
    sa.Column('estatus', sa.Enum('ACTIVO', 'INACTIVO', name='supplierstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_is_deleted'), 'suppliers', ['is_deleted'], unique=False)
    op.create_table('trailers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_economico', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.Enum('CAJA_SECA', 'PLATAFORMA', 'REFRIGERADO', 'TANQUE', name='trailertype', native_enum=False), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('placas', sa.String(length=15), nullable=True),
    sa.Column('capacidad_carga_ton', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estatus', sa.Enum('DISPONIBLE', 'EN_USO', 'TALLER', 'BAJA', name='unitstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_economico')
    )
    op.create_index(op.f('ix_trailers_is_deleted'), 'trailers', ['is_deleted'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_economico', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('placas', sa.String(length=15), nullable=True),
    sa.Column('numero_serie', sa.String(length=50), nullable=True),
    sa.Column('tipo_vehiculo', sa.Enum('TRACTO', 'TORTON', 'RABON', name='vehicletype', native_enum=False), nullable=False),
    sa.Column('capacidad_tanque', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('km_actual', sa.Integer(), nullable=True),
    sa.Column('chofer_id', sa.Integer(), nullable=True),
    sa.Column('estatus', sa.Enum('DISPONIBLE', 'EN_RUTA', 'TALLER', 'BAJA', name='vehiclestatus', native_enum=False), nullable=False),
    sa.Column('proximo_servicio_km', sa.Integer(), nullable=True),
    sa.Column('fecha_proximo_servicio', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chofer_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_economico')
    )
    op.create_index(op.f('ix_vehicles_is_deleted'), 'vehicles', ['is_deleted'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.Enum('factura_vencida', 'factura_por_vencer', 'viaje_programado', 'viaje_en_ruta', 'viaje_completado', 'tracking_update', 'stock_bajo', 'servicio_proximo', name='notificationtype', native_enum=False), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('prioridad', sa.Enum('baja', 'media', 'alta', 'urgente', name='notificationpriority', native_enum=False), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('referencia_tipo', sa.String(length=50), nullable=True),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_deleted'), 'notifications', ['is_deleted'], unique=False)
    op.create_table('requisitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('fecha_requerida', sa.Date(), nullable=True),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('estatus', sa.Enum('BORRADOR', 'PENDIENTE', 'APROBADA', 'RECHAZADA', 'COMPLETADA', name='requisitionstatus'), nullable=False),
    sa.Column('total_estimado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_requisitions_is_deleted'), 'requisitions', ['is_deleted'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_viaje', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('chofer_id', sa.Integer(), nullable=True),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('remolque1_id', sa.Integer(), nullable=True),
    sa.Column('remolque2_id', sa.Integer(), nullable=True),
    sa.Column('dolly_id', sa.Integer(), nullable=True),
    sa.Column('origen', sa.String(length=200), nullable=True),
    sa.Column('destino', sa.String(length=200), nullable=True),
    sa.Column('distancia_km', sa.Integer(), nullable=True),
    sa.Column('tipo_carga', sa.String(length=200), nullable=True),
    sa.Column('peso_toneladas', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('contenedores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_programada', sa.Date(), nullable=True),
    sa.Column('fecha_salida', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_entrega_estimada', sa.Date(), nullable=True),
    sa.Column('fecha_entrega_real', sa.DateTime(timezone=True), nullable=True),
    sa.Column('km_salida', sa.Integer(), nullable=True),
    sa.Column('km_llegada', sa.Integer(), nullable=True),
    sa.Column('tarifa_cliente', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('estatus', sa.Enum('programado', 'asignado', 'en_ruta', 'completado', 'cancelado', name='tripstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chofer_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['dolly_id'], ['dollies.id'], ),
    sa.ForeignKeyConstraint(['remolque1_id'], ['trailers.id'], ),
    sa.ForeignKeyConstraint(['remolque2_id'], ['trailers.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_viaje')
    )
    op.create_index(op.f('ix_trips_is_deleted'), 'trips', ['is_deleted'], unique=False)
    op.create_table('vehicle_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('tipo_servicio', sa.Enum('PREVENTIVO', 'CORRECTIVO', 'LLANTAS', 'AFINACION', name='servicetype', native_enum=False), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('km_servicio', sa.Integer(), nullable=False),
    sa.Column('fecha_servicio', sa.Date(), nullable=False),
    sa.Column('costo', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('proveedor', sa.String(length=200), nullable=True),
    sa.Column('proximo_servicio_km', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_services_is_deleted'), 'vehicle_services', ['is_deleted'], unique=False)
    op.create_table('diesel_loads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('chofer_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('patio', 'gasolinera', name='dieselloadtype', native_enum=False), nullable=False),
    sa.Column('litros', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_por_litro', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('costo_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('km_odometro', sa.Integer(), nullable=True),
    sa.Column('fecha_carga', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chofer_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diesel_loads_is_deleted'), 'diesel_loads', ['is_deleted'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_orden', sa.Date(), nullable=False),
    sa.Column('fecha_entrega_esperada', sa.Date(), nullable=True),
    sa.Column('fecha_entrega_real', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estatus', sa.Enum('PENDIENTE', 'ENVIADA', 'PARCIAL', 'RECIBIDA', 'CANCELADA', name='purchaseorderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_purchase_orders_is_deleted'), 'purchase_orders', ['is_deleted'], unique=False)
    op.create_table('requisition_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('precio_estimado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requisition_items_is_deleted'), 'requisition_items', ['is_deleted'], unique=False)
    op.create_table('trip_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('actualizacion', 'incidencia', 'documento', 'estatus_change', name='commenttype', native_enum=False), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('genera_notificacion', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_comments_is_deleted'), 'trip_comments', ['is_deleted'], unique=False)
    op.create_table('trip_expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('tipo_gasto', sa.Enum('caseta', 'viaticos', 'combustible', 'maniobras', 'pension', 'estacionamiento', 'otro', name='expensetype', native_enum=False), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_gasto', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_expenses_is_deleted'), 'trip_expenses', ['is_deleted'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'salida', name='movementtype'), nullable=False),
    sa.Column('razon', sa.Enum('compra', 'devolucion', 'ajuste', 'consumo', 'mantenimiento', 'otro', name='movementreason'), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('fecha_movimiento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stock_resultante', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('referencia', sa.String(length=200), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_inventory_movements_is_deleted'), 'inventory_movements', ['is_deleted'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_factura', sa.String(length=100), nullable=False),
    sa.Column('folio_fiscal', sa.String(length=40), nullable=True),
    sa.Column('tipo', sa.Enum('POR_PAGAR', 'POR_COBRAR', name='invoicetype'), nullable=False),
    sa.Column('estatus', sa.Enum('PENDIENTE', 'PARCIAL', 'PAGADA', 'CANCELADA', name='invoicestatus'), nullable=False),
    sa.Column('fecha_factura', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('archivo_pdf', sa.String(length=500), nullable=True),
    sa.Column('archivo_xml', sa.String(length=500), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('concepto', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_is_deleted'), 'invoices', ['is_deleted'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cantidad_recibida', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_is_deleted'), 'purchase_order_items', ['is_deleted'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.Enum('TRANSFERENCIA', 'CHEQUE', 'EFECTIVO', 'TARJETA', 'OTRO', name='paymentmethod'), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('archivo_comprobante', sa.String(length=500), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_is_deleted'), 'payments', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_is_deleted'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_purchase_order_items_is_deleted'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_invoices_is_deleted'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_inventory_movements_is_deleted'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_trip_expenses_is_deleted'), table_name='trip_expenses')
    op.drop_table('trip_expenses')
    op.drop_index(op.f('ix_trip_comments_is_deleted'), table_name='trip_comments')
    op.drop_table('trip_comments')
    op.drop_index(op.f('ix_requisition_items_is_deleted'), table_name='requisition_items')
    op.drop_table('requisition_items')
    op.drop_index(op.f('ix_purchase_orders_is_deleted'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_diesel_loads_is_deleted'), table_name='diesel_loads')
    op.drop_table('diesel_loads')
    op.drop_index(op.f('ix_vehicle_services_is_deleted'), table_name='vehicle_services')
    op.drop_table('vehicle_services')
    op.drop_index(op.f('ix_trips_is_deleted'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_requisitions_is_deleted'), table_name='requisitions')
    op.drop_table('requisitions')
    op.drop_index(op.f('ix_notifications_is_deleted'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_vehicles_is_deleted'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trailers_is_deleted'), table_name='trailers')
    op.drop_table('trailers')
    op.drop_index(op.f('ix_suppliers_is_deleted'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_is_deleted'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_inventory_items_is_deleted'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_drivers_is_deleted'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_dollies_is_deleted'), table_name='dollies')
    op.drop_table('dollies')
    op.drop_index(op.f('ix_clients_is_deleted'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
